language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - TYPO3_VERSION=^6.2 COVERAGE=0
  - TYPO3_VERSION=^7.6 COVERAGE=0

matrix:
  include:
      - env: TYPO3_VERSION=^6.2 COVERAGE=0
        php: 5.5
      - env: TYPO3_VERSION=^7.6 COVERAGE=1
        php: 7.0

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms=$TYPO3_VERSION
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - export "UNIT_XML"=`find . -name 'UnitTests.xml' -type f`
  - mkdir -p build/logs

script:
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --colors -c $UNIT_XML Tests/Unit
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --colors -c $UNIT_XML --coverage-text --coverage-clover build/logs/clover.xml Tests/Unit/
    fi

after_script:
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      travis_retry php .Build/bin/coveralls -v
    fi
